Cfg.BlackWeapons = {
    "WEAPON_ASSAULTRIFLE_MK2",
    "WEAPON_SMG_MK2",
    "WEAPON_COMBATMG_MK2",
    "WEAPON_HEAVYSNIPER_MK2",
    "WEAPON_GRENADELAUNCHER",
    "WEAPON_RAILGUN",
   --"WEAPON_SNSPISTOL_MK2",
   --"WEAPON_REVOLVER_MK2",
    --"WEAPON_SMOKEGRENADE",
    "WEAPON_PROXMINE",
    --"WEAPON_GRENADELAUNCHER_SMOKE",
    --"WEAPON_SPECIALCARBINE_MK2",
    --"WEAPON_BULLPUPRIFLE_MK2",
    --"WEAPON_PUMPSHOTGUN_MK2",
    --"WEAPON_MARKSMANRIFLE_MK2",
    --"WEAPON_GARBAGEBAG",
    "WEAPON_RAYCARBINE",
    "WEAPON_PIPEBOMB",
    "WEAPON_COMPACTLAUNCHER",
    "WEAPON_FIREWORK",
    "WEAPON_GREANDE",
    "WEAPON_ROCKET",
    "WEAPON_RPG",
    "WEAPON_MINIGUN",
    "WEAPON_HOMINGLAUNCHER"
}
--GetStatusOfTextureDownload
Cfg.BlackListedTextures = {
    'tamerelapute',
    'helicopterhud',
    'deadline',
    --'shopui_title_sm_hangar',
    'rampage_tr_main', -- rampage menu
    'digitaloverlay',
    'setMenuProperty',
    'bobylebg',
    'mpmissmarkers256',
    'titleBackgroundSprite.dict',
    'titleBackgroundSprite',
    'meow',
    'meow2', -- Menu js 
    'hunting',
    'shopui_title_graphics_franklin',
    'rk36Zr2W8ONhMfo7UavTQ.dict',
    'rk36Zr2W8ONhMfo7UavTQ.text',
    'leaderboard_car_colour_bg',
    'titleBackgroundSprite.name',
    'textureDict',
    'txtRatio',
    'screenX',
    'screenY',
    'heisthud',
    'main_gradient',
    'leaderboard_players_icon',
    'mparrow',
    'pilotschool',
    'hudarrow',
    'JTD.dict',
    'JTD.text',
    '0xE7FFAE5EBF23D890',
    'ISMMENU',
    'ISMMENUHeader',
    'ISMMENULogo',
    'corona_shade',
    'timerbar_sr',
    'timer_cross',
    'timer_tick',
    'header',
    'subTitlebackground',
    'bottomsubTitlebackground',
    'subTitleText',
    'self_pedchanger',
    'veh_nextsprite',
    'wep_ped',
    'srange_gen',
    'hit_cross',
    'Invoke',
    'cock_moscow',
    'menu_gif',
    'hud_lock',
    'hud_corner',
    'cockmenuuu',
    'loadhack',
    'mpentry',
    'mp_modenotselected_gradient',
    'shared',
    'menuarrow_32',
    'mp_modeselected_gradient',
    'REAPER2',
    'REAPER3',
    'REAPER8',
    'REAPER10',
    'REAPER6',
    'REAPER7',
    'REAPER5',
    'lhs_bg',
    'REAPER23',
    'REAPER24',
    'REAPER16',
    'REAPER15',
    'mprankbadge',
    'globe_bg',
    'REAPER21',
    'REAPER22',
    'REAPER20',
    'REAPER19',
    'REAPER18',
    'REAPER17',
    'REAPER14',
    'REAPER13',
    'REAPER12',
    'REAPER11',
    'REAPER9',
    'REAPER4',
    'REAPER1',
    'deadline_trail_01',
    'currentMenu',
    'HugeWare_SDGUHSFDIGDFG',
    'textureDict_SDGHSIUDGSDG',
    'leaderboard_voteblank_icon',
    'mpweaponsgang1',
    'HydroMenu',
    'HydroMenuHeader',
    'HydroMenuLogo',
    'MButtonSpriteScale_DSGJHSDIGSDG',
    'leaderboard_players_icon',
    'leaderboard_deaths_icon',
    'leaderboard_kills_icon',
    'leaderboard_transport_car_icon',
    'leaderboard_friends_icon',
    'leaderboard_globe_icon',
    'custompistolW',
    'pistolW',
    'Money',
    'arme',
    'createvehicule',
    'OverLateMENU',
    'OverLateMENUHeader',
    'MenyooExtras'
}

Cfg.BlacklistedObjectByPlayer = {    
    "prop_container_05a"
}

Cfg.BlacklistObject = {
    "stt_prop_stunt_track_uturn",
    "cs2_11_sea_marina_xr_rocks_03_lod",
    "hei_prop_carrier_radar_1_l1",
    "cs3_08b_rsn_db_aliencover_0001cs3_08b_rsn_db_aliencover_0001_a",
    "stt_prop_stunt_track_turnice",
    "apa_mp_apa_crashed_usaf_01a",
    "stt_prop_stunt_track_hill",
    "prop_gold_cont_01",
    "v_res_mexball",
    "p_crahsed_heli_s",
    "sr_prop_spec_tube_xxs_01a",
    "prop_flamingo",
    "prop_flag_columbia",
    "p_cablecar_s",
    "prop_weed_01",
    "prop_container_ld_pu",
    "stt_prop_stunt_tube_l",
    "stt_prop_stunt_track_dwuturn",
    "prop_fnclink_05crnr1",
    "xs_prop_hamburgher_wl",
    "xs_prop_plastic_bottle_wl",
    "cs1_lod3_terrain_slod3_01",
    "p_spinning_anus_s",
    "cs4_lod_01_slod3",
    "stt_prop_ramp_adj_flip_m",
    "stt_prop_ramp_adj_flip_mb",
    "stt_prop_ramp_adj_flip_s",
    "stt_prop_ramp_adj_flip_sb",
    "stt_prop_ramp_adj_hloop",
    "stt_prop_ramp_adj_loop",
    "stt_prop_ramp_jump_l",
    "stt_prop_ramp_jump_m",
    "stt_prop_ramp_jump_s",
    "stt_prop_ramp_jump_xl",
    "stt_prop_ramp_jump_xs",
    "stt_prop_ramp_jump_xxl",
    "stt_prop_ramp_multi_loop_rb",
    "stt_prop_ramp_spiral_l",
    "stt_prop_ramp_spiral_l_l",
    "stt_prop_ramp_spiral_l_m",
    "stt_prop_ramp_spiral_l_s",
    "stt_prop_ramp_spiral_l_xxl",
    "stt_prop_ramp_spiral_m",
    "stt_prop_ramp_spiral_s",
    "stt_prop_ramp_spiral_xxl",
    "stt_prop_stunt_track_dwslope30",
    "stt_prop_stunt_track_start",
    "stt_prop_stunt_track_slope45",
    "stt_prop_stunt_track_slope30",
    "stt_prop_stunt_track_slope15",
    "stt_prop_stunt_track_short",
    "stt_prop_stunt_track_sh45_a",
    "stt_prop_stunt_track_sh45",
    "stt_prop_stunt_track_sh30",
    "stt_prop_stunt_track_sh15",
    "stt_prop_stunt_track_otake",
    "stt_prop_stunt_track_link",
    "stt_prop_stunt_track_jump",
    "stt_prop_stunt_track_hill2",
    "stt_prop_stunt_track_hill",
}

Cfg.BlackListVeh = {
	"AVENGER",
	--"RHINO",
    "limo2",
    --"LAZER",
    "BLIMP2",
    "SAVAGE",
  --  "insurgent",
    "BLIMP3",
	"CARGOPLANE",
    --"APC",
    "oppressor2",
    "Khanjali",
	"JET",
	"HYDRA",
	"CUTTER",
	"BULLDOZER",
	"DELUXO",
    "THRUSTER",
	--"TITAN",
	--"BESRA",
	"BUZZARD",
	"ZR380"
}

Cfg.WhiteListedPed = {
    "mp_m_freemode_01",
    "mp_f_freemode_01",

    -- pour mistyv
    "a_m_m_business_01",
    "s_m_m_trucker_01",
    "a_c_fish",
    "s_m_m_linecook",
    "a_m_o_acult_02",
    "s_m_y_chef_01",
    "a_c_deer",
    "ig_solomon",
    "a_m_m_og_boss_01",
    "mp_m_weed_01",
    "a_m_m_og_boss_01",
    "a_m_y_clubcust_01",
    "s_m_m_doctor_01",
    "s_m_y_ammucity_01",
    "cs_bankman",
    "ig_casey",
    "ig_benny",
    "s_f_y_cop_01",
    "s_m_y_cop_01"
}

Cfg.BlackListPedList = {
    "s_m_y_swat_01",
    'U_M_Y_Zombie_01',
--    "A_C_MtLion",
    "A_M_Y_ACult_01",
    "s_m_m_movspace_01",
    "mp_m_niko_01",
  --  "a_m_o_acult_01",
    'u_m_y_babyd',
    "s_m_y_prismuscl_01",
    's_m_m_movalien_01',
    'a_c_chimp',
    's_m_m_movallien_01',
    "s_m_m_strperf_01",
    "a_f_m_fatcult_01",
  --  "a_m_m_hasjew_01",
    --"a_m_y_acult_02",
    "a_m_y_jetski_01",
  --  "a_m_y_musclbeac_01"
}

Cfg.BlacklistedEvent = { -- client
    "AdminMenu:giveCash",
    "HCheat:TempDisableDetection",
    "payforplayer2",
    "_chat:messageEntered",
    "ambulancier:selfRespawn"
}

--- from lynx cheats
Cfg.BlackListHash = {
    0x34315488,
    0x6A27FEB1, 0xCB2ACC8,
    0xC6899CDE, 0xD14B5BA3,
    0xD9F4474C, 0x32A9996C,
    0x69D4F974, 0xCAFC1EC3,
    0x79B41171, 0x1075651,
    0xC07792D4, 0x781E451D,
    0x762657C6, 0xC2E75A21,
    0xC3C00861, 0x81FB3FF0,
    0x45EF7804, 0xE65EC0E4,
    0xE764D794, 0xFBF7D21F,
    0xE1AEB708, 0xA5E3D471,
    0xD971BBAE, 0xCF7A9A9D,
    0xC2CC99D8, 0x8FB233A4,
    0x24E08E1F, 0x337B2B54,
    0xB9402F87, 0x4F2526DA
}