RegisterNetEvent("core:CokeEffect")
AddEventHandler("core:CokeEffect", function()
    local playerPed = PlayerPedId()
    DoScreenFadeOut(800)
    Wait(800)
    --DoScreenFadeOut(10)
    SetTimecycleModifier("spectator5")
    SetPedMotionBlur(playerPed, true)
    SetPedIsDrunk(playerPed, true)
    SetPedMoveRateOverride(PlayerId(), 5.0)
    SetRunSprintMultiplierForPlayer(PlayerId(), 1.10)
    AnimpostfxPlay("DrugsTrevorClownsFight", 10000001, true)
    ShakeGameplayCam("VIBRATE_SHAKE", 2.5)
    DoScreenFadeIn(800)
    Wait(100000)
    DoScreenFadeOut(800)
    Wait(800)
    SetPedMoveRateOverride(PlayerId(), 1.0)
    SetRunSprintMultiplierForPlayer(PlayerId(), 1.0)
    SetPedIsDrunk(GetPlayerPed(-1), false)
    SetPedMotionBlur(playerPed, false)
    ResetPedMovementClipset(GetPlayerPed(-1))
    AnimpostfxStopAll()
    ShakeGameplayCam("VIBRATE_SHAKE", 0.0)
    SetTimecycleModifierStrength(0.0)
    DoScreenFadeIn(800)
end)

RegisterNetEvent("core:HeroineEffect")
AddEventHandler("core:HeroineEffect", function()
    local playerPed = PlayerPedId()
    DoScreenFadeOut(800)
    Wait(800)
    --DoScreenFadeOut(10)
    SetTimecycleModifier("spectator5")
    SetPedMotionBlur(playerPed, true)
    SetPedIsDrunk(playerPed, true)
    SetPedMoveRateOverride(PlayerId(), 5.0)
    SetRunSprintMultiplierForPlayer(PlayerId(), 1.10)
    AnimpostfxPlay("DrugsTrevorClownsFight", 10000001, true)
    ShakeGameplayCam("VIBRATE_SHAKE", 2.5)
    DoScreenFadeIn(800)
    Wait(100000)
    DoScreenFadeOut(800)
    Wait(800)
    SetPedMoveRateOverride(PlayerId(), 1.0)
    SetRunSprintMultiplierForPlayer(PlayerId(), 1.0)
    SetPedIsDrunk(GetPlayerPed(-1), false)
    SetPedMotionBlur(playerPed, false)
    ResetPedMovementClipset(GetPlayerPed(-1))
    AnimpostfxStopAll()
    ShakeGameplayCam("VIBRATE_SHAKE", 0.0)
    SetTimecycleModifierStrength(0.0)
    DoScreenFadeIn(800)
end)

RegisterNetEvent("core:WeedEffect")
AddEventHandler("core:WeedEffect", function()
    local playerPed = PlayerPedId()
    DoScreenFadeOut(800)
    Wait(800)
    RequestAnimSet("MOVE_M@DRUNK@slightlydrunk")
    while not HasAnimSetLoaded("MOVE_M@DRUNK@slightlydrunk") do
        Wait(0)
    end
    SetTimecycleModifier("spectator6")
    SetPedMotionBlur(playerPed, true)
    SetPedMovementClipset(playerPed, "MOVE_M@DRUNK@slightlydrunk", true)
    SetPedIsDrunk(playerPed, true)
    AnimpostfxPlay("ChopVision", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 1.0)
    DoScreenFadeIn(800)
    Wait(100000)
    --  after wait stop all effects
    DoScreenFadeOut(800)
    Wait(800)
    SetPedMoveRateOverride(PlayerId(), 1.0)
    SetRunSprintMultiplierForPlayer(PlayerId(), 1.0)
    SetPedIsDrunk(GetPlayerPed(-1), false)
    SetPedMotionBlur(playerPed, false)
    ResetPedMovementClipset(GetPlayerPed(-1))
    AnimpostfxStopAll()
    ShakeGameplayCam("DRUNK_SHAKE", 0.0)
    SetTimecycleModifierStrength(0.0)
    DoScreenFadeIn(800)
end)

RegisterNetEvent("core:MethEffect")
AddEventHandler("core:MethEffect", function()
    local playerPed = PlayerPedId()
    DoScreenFadeOut(800)
    Wait(800)
    RequestAnimSet("move_m@drunk@slightlydrunk")
    while not HasAnimSetLoaded("move_m@drunk@slightlydrunk") do
        Wait(0)
    end
    SetPedMotionBlur(playerPed, true)
    SetPedMovementClipset(playerPed, "move_m@drunk@slightlydrunk", true)
    SetPedIsDrunk(playerPed, true)
    SetTimecycleModifier("spectator5")
    AnimpostfxPlay("SuccessMichael", 10000001, true)
    ShakeGameplayCam("DRUNK_SHAKE", 1.5)
    DoScreenFadeIn(800)
    Wait(100000)
    --  after wait stop all effects
    DoScreenFadeOut(800)
    Wait(800)
    SetPedMoveRateOverride(PlayerId(), 1.0)
    SetRunSprintMultiplierForPlayer(PlayerId(), 1.0)
    SetPedIsDrunk(GetPlayerPed(-1), false)
    SetPedMotionBlur(playerPed, false)
    ResetPedMovementClipset(GetPlayerPed(-1))
    AnimpostfxStopAll()
    ShakeGameplayCam("DRUNK_SHAKE", 0.0)
    SetTimecycleModifierStrength(0.0)
    DoScreenFadeIn(800)
end)

-- RegisterCommand("reset", function ()
--     SetPedMoveRateOverride(PlayerId(),1.0)
--     SetRunSprintMultiplierForPlayer(PlayerId(),1.0)
--     SetPedIsDrunk(GetPlayerPed(-1), false)
--     SetPedMotionBlur(playerPed, false)
--     ResetPedMovementClipset(GetPlayerPed(-1))
--     AnimpostfxStopAll()
--     ShakeGameplayCam("DRUNK_SHAKE", 0.0)
--     SetTimecycleModifierStrength(0.0)
-- end)

-- RegisterCommand("coke", function ()
--     TriggerEvent("core:CokeEffect")
-- end)

-- RegisterCommand("weed", function ()
--     TriggerEvent("core:WeedEffect")
-- end)

-- RegisterCommand("meth", function ()
--     TriggerEvent("core:MethEffect")
-- end)
