items = {

    ["saphir"] = { label = "Saphir", weight = 1.00, type = "items", cols = 1, rows = 1 },

    ["banana"] = { label = "La Sainte Banane", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["money"] = { label = "Argent", weight = 0.0, type = "items", cols = 1, rows = 1 },
    ["water"] = { label = "Bouteille d eau", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["juicep"] = { label = "Jus de pomme", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["cocktail"] = { label = "Cocktail", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["tapas"] = { label = "Tapas", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["burger"] = { label = "Hamburger", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["champ"] = { label = "Champagne", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["pasta"] = { label = "Pâtes", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["alcohol"] = { label = "Bouteille d alcool", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["megaphone"] = { label = "Mégaphone", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["handcuff"] = { label = "Menottes", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["note"] = { label = "Bloc-notes", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["phone"] = { label = "Téléphone", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true },
    ["radio"] = { label = "Radio", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["skate"] = { label = "Skate", weight = 0.10, type = "items", cols = 1, rows = 1 },

    ["tshirt"] = { label = "T-shirt", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["pant"] = { label = "Pantalon", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["hat"] = { label = "Chapeau", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["access"] = { label = "Accessoire", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["glasses"] = { label = "Lunettes", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["feet"] = { label = "Chaussures", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["montre"] = { label = "Montre", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["bague"] = { label = "Bague", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["ongle"] = { label = "Ongles", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["piercing"] = { label = "Piercing", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["bracelet"] = { label = "Bracelet", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["bouclesoreilles"] = { label = "Boucles d'oreilles", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["collier"] = { label = "Collier", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["mask"] = { label = "Masque", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["outfit"] = { label = "Tenue", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["weed"] = { label = "Weed", weight = 0.50, type = "items", cols = 1, rows = 1 },
    ["coke"] = { label = "Cocaine", weight = 0.50, type = "items", cols = 1, rows = 1 },
    ["heroine"] = { label = "Heroïne", weight = 0.50, type = "items", cols = 1, rows = 1 },
    ["meth"] = { label = "Meth", weight = 0.50, type = "items", cols = 1, rows = 1 },
    ["bequille"] = { label = "Béquille", weight = 0.50, type = "items", cols = 1, rows = 1 },
    ["froulant"] = { label = "Fauteuil roulant", weight = 2.00, type = "items", cols = 1, rows = 1 },
    ["meuleuse"] = { label = "Meuleuse", weight = 1.00, type = "items", cols = 1, rows = 1 },
    ["surfboard"] = { label = "Planche de surf", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["ptshirt"] = { label = "T-shirt", weight = 0.10, type = "clothes", cols = 1, rows = 1},
    ["ppant"] = { label = "Pantalon", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["paccs"] = { label = "Accessoire", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["phat"] = { label = "Chapeau", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["pglasses"] = { label = "Lunettes", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    

    -- ["bag"] = { label = "Sac", weight = 0.10, type = "clothes", cols = 1, rows = 1 },
    ["gps"] = { label = "GPS", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["key"] = { label = "Clés", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["badgel"] = { label = "Badge LSPD", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["badgep"] = { label = "Badge presse", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["driverlicense"] = { label = "Permis de conduire", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["identitycards"] = { label = "Carte d identité", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["identitycard"] = { label = "Carte d identité", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["creditcard"] = { label = "Carte bancaire", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["band"] = { label = "Bandage", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["pad"] = { label = "Pansement", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["pad2"] = { label = "Pansement Hello Kitty", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["pad3"] = { label = "Pansement Bob L'éponge", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["medic"] = { label = "Médicament", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["poudre"] = { label = "Kit test de poudre", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["crochet"] = { label = "Outil de crochetage", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["jumelle"] = { label = "Jumelle", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["medikit"] = { label = "Trousse de soin", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["cleankit"] = { label = "Kit de nettoyage", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["repairkit"] = { label = "Kit de réparation", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["cig"] = { label = "Cigarettes", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["rod"] = { label = "Canne à pêche", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["lstcard"] = { label = "Carte Pro LST", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["kevlarle"] = { label = "Kevlar léger", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["kevlarm"] = { label = "Kevlar moyen", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["kevlarlo"] = { label = "Kevlar lourd", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["can"] = { label = "Canette vide", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["soda"] = { label = "Soda", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["ecola"] = { label = "eCola", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["sprunk"] = { label = "Sprunk", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["drill"] = { label = "Perceuse", weight = 0.50, type = "items", cols = 2, rows = 2 },
    ["umbrella"] = { label = "Parapluie", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["bread"] = { label = "Pain", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["beef"] = { label = "Boeuf", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["cheese"] = { label = "Fromage", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["chicken"] = { label = "Poulet", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["salad"] = { label = "Salade", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["tomato"] = { label = "Tomate", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["sauce"] = { label = "Sauce", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["fish"] = { label = "Poisson", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["galette"] = { label = "Galette", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["oignon"] = { label = "Oignon", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["egg"] = { label = "Oeuf", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["flour"] = { label = "Farine", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["sugar"] = { label = "Sucre", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["butter"] = { label = "Beurre", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["choco"] = { label = "Chocolat", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["algue"] = { label = "Algue", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["rice"] = { label = "Riz", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["avocado"] = { label = "Avocat", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["jaeger"] = { label = "Jaegermeister ", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["salmon"] = { label = "Saumon", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["cucumber"] = { label = "Concombre", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["sesam"] = { label = "Sésame", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["vinaigrer"] = { label = "Vinaigre de riz", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["cups"] = { label = "Gobelet", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["nouille"] = { label = "Nouilles", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["chou"] = { label = "Chou", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["soja"] = { label = "Soja", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["nougat"] = { label = "Nougat", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["litchi"] = { label = "Litchis", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["mint"] = { label = "Menthe", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["lemon"] = { label = "Citron", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["juice"] = { label = "Jus", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["coffee"] = { label = "Café", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["milk"] = { label = "Lait", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["tea"] = { label = "Thé", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["water2"] = { label = "Eau gazeuse", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["caprisun"] = { label = "Capri Sun", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["whisky"] = { label = "Whisky", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["jet27"] = { label = "Jet 27", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["vodka"] = { label = "Vodka", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["gin"] = { label = "Gin", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["tequila"] = { label = "Tequila", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["beer"] = { label = "Bière", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["rhum"] = { label = "Rhum", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["wine"] = { label = "Vin", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["sake"] = { label = "Saké", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["chainebg"] = { label = "Chaîne bas de gamme", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["chainehq"] = { label = "Chaîne de haute qualité", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["penden"] = { label = "Pendentif en toc", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["penden2"] = { label = "Pendentif qualitatif", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["mecanismel"] = { label = "Mécanisme de montre de luxe", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["mecanismebg"] = { label = "Mécanisme de montre bas de gamme", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["camerap"] = { label = "Caméra sur pied", weight = 1.50, type = "items", cols = 2, rows = 2 },
    ["camerab"] = { label = "Caméra bras", weight = 1.50, type = "items", cols = 2, rows = 2 },
    ["camera"] = { label = "Appareil photo", weight = 1.00, type = "items", cols = 1, rows = 1 },
    ["cameraw"] = { label = "Caméra", weight = 1.00, type = "items", cols = 1, rows = 1 },
    ["microm"] = { label = "Microphone main", weight = 0.50, type = "items", cols = 1, rows = 1 },
    ["microc"] = { label = "Microphone cravate", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["microp"] = { label = "Microphone perche", weight = 1.50, type = "items", cols = 2, rows = 1 },
    ["fishburger"] = { label = "Fishburger", weight = 0.30, type = "items", cols = 1, rows = 1 },
    ["panini"] = { label = "Panini", weight = 0.30, type = "items", cols = 1, rows = 1 },
    ["catpat"] = { label = "Cat Pat", weight = 0.30, type = "items", cols = 1, rows = 1 },
    ["barbamilk"] = { label = "Barba'Milk", weight = 0.30, type = "items", cols = 1, rows = 1 },
    ["chatmallow"] = { label = "Chat'Mallow", weight = 0.30, type = "items", cols = 1, rows = 1 },
    ["bubbletea"] = { label = "Bubble Tea", weight = 0.30, type = "items", cols = 1, rows = 1 },
    
    ["kitty"] = { label = "Kitty Toy Rose", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["kitty2"] = { label = "Kitty Toy Bleu", weight = 0.10, type = "items", cols = 1, rows = 1 },

    ["KittyToyArcEnCiel"] = { label = "Kitty Toy Arc En Ciel", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["KittyToyDark"] = { label = "Kitty Toy Dark", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["KittyToyFlower"] = { label = "Kitty Toy Flower", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["KittyToyGris"] = { label = "Kitt Toy Gris", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["KittyToyJaune"] = { label = "Kitty Toy Jaune", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["KittyToyVert"] = { label = "Kitty Toy Vert", weight = 0.10, type = "items", cols = 1, rows = 1 },
    
    ["wrapp"] = { label = "Wrap poulet", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["wrapb"] = { label = "Wrap boeuf", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["saladece"] = { label = "Salade César", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["saladeco"] = { label = "Salade composée", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["carpe"] = { label = "Carpe", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["bar"] = { label = "Bar", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["merlan"] = { label = "Merlan", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["saumon"] = { label = "Saumon", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["calamar"] = { label = "Calamar", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["tacos"] = { label = "Tacos", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["fajitas"] = { label = "Fajitas", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["tortillas"] = { label = "Tortillas", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["quesadillas"] = { label = "Quesadillas", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["burrito"] = { label = "Burrito", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["beignet"] = { label = "Beignet", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["mochi"] = { label = "Mochi", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["sundae"] = { label = "Sundae", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["tiramisu"] = { label = "Tiramisu", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["cookie"] = { label = "Cookie", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["pilon"] = { label = "Pilon de poulet", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["nuggets"] = { label = "Nuggets de poulet", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["bucket"] = { label = "Bucket de poulet", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["wings"] = { label = "Wings de poulet", weight = 0.10, type = "items", cols = 1, rows = 1 },


    ["requin"] = { label = "Requin", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["dauphin"] = { label = "Dauphin", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["orc"] = { label = "Orque", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["raie"] = { label = "Raie", weight = 0.10, type = "items", cols = 1, rows = 1 },

    ["Esturgeon"] = { label = "Esturgeon", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["PoissonNapoleon"] = { label = "PoissonNapoleon", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["PoissonScie"] = { label = "PoissonScie", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["Baleine"] = { label = "Baleine", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["Murene"] = { label = "Murène", weight = 0.10, type = "items", cols = 1, rows = 1 },

    ["algues"] = { label = "Algues", weight = 0.10, type = "items", cols = 1, rows = 1 },



    ["donutn"] = { label = "Donut nature", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["donutc"] = { label = "Donut chocolat", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["sushic"] = { label = "Sushi californien", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["maki"] = { label = "Maki", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["ramenp"] = { label = "Ramen poulet", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["ramenb"] = { label = "Ramen boeuf", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["nemp"] = { label = "Nems poulet", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["nemb"] = { label = "Nems boeuf", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["mojito"] = { label = "Mojito", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["punch"] = { label = "Punch", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["pinacolada"] = { label = "Pina Colada", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["margarita"] = { label = "Margarita", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["sexotb"] = { label = "Sex on the Beach", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["irishc"] = { label = "Irish Coffee", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["tabc"] = { label = "Tableau commun", weight = 1.00, type = "items", cols = 2, rows = 2 },
    ["tabpc"] = { label = "Tableu peu commun", weight = 1.00, type = "items", cols = 2, rows = 2 },
    ["tabr"] = { label = "Tableau rare", weight = 1.00, type = "items", cols = 2, rows = 2 },
    ["consolejv"] = { label = "Console de jeu", weight = 1.50, type = "items", cols = 2, rows = 2 },
    ["tv"] = { label = "Télévision écran plat", weight = 2.00, type = "items", cols = 2, rows = 2 },
    ["tv2"] = { label = "Télévision bas de gamme", weight = 1.50, type = "items", cols = 2, rows = 2 },
    ["laptop"] = { label = "Ordinateur portable", weight = 1.00, type = "items", cols = 2, rows = 2 },
    ["jewel"] = { label = "Bijoux", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["diamond"] = { label = "Diamant", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["perfume"] = { label = "Parfum", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["tablet"] = { label = "Tablette", weight = 1.00, type = "items", cols = 1, rows = 1 },
    ["enceinte"] = { label = "Enceinte", weight = 1.50, type = "items", cols = 2, rows = 2 },
    ["manettejv"] = { label = "Manette de jeu", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["guitar"] = { label = "Guitare de Rockstar", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["bouteille2"] = { label = "Bouteille plaqué or", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["champagne_pack"] = { label = "Caisse de champagne", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["golf_bag"] = { label = "Sac de golf", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["pince"] = { label = "Pince à cheveux", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["bike"] = { label = "Vélo", weight = 2.0, type = "items", cols = 2, rows = 2 },
    ["plate"] = { label = "Plaque", weight = 1.0, type = "items", cols = 1, rows = 1 },


    -- MUNITION

    ["ammo_pistol"] = { label = "Pistol Magazine", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["ammo_flare"] = { label = "Flaregun Ammo", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["ammo_sub"] = { label = "Submachine Magazine", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["ammo_shotgun"] = { label = "ShotGun Magazine", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["ammo_rifle"] = { label = "Rifle Magazine", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["ammo_snip"] = { label = "Sniper Magazine", weight = 0.10, type = "items", cols = 1, rows = 1 },

    ["ammo_heavy"] = { label = "Heavy Magazine", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["ammo_rocket"] = { label = "Rocket", weight = 0.10, type = "items", cols = 1, rows = 2 },

    ["ammo_beambag"] = { label = "Beambag Ammo", weight = 0.10, type = "items", cols = 1, rows = 1 },

    ["ammobox_pistol"] = { label = "Pistol Magazine Box", weight = 0.20, type = "items", cols = 1, rows = 1 },
    ["ammobox_flare"] = { label = "Flaregun Ammo Box", weight = 0.15, type = "items", cols = 1, rows = 1 },
    ["ammobox_sub"] = { label = "Sub Magazine Box", weight = 0.20, type = "items", cols = 1, rows = 1 },
    ["ammobox_shotgun"] = { label = "Shotgun Magazine Box", weight = 0.20, type = "items", cols = 1, rows = 1 },
    ["ammobox_rifle"] = { label = "Rifle Magazine Box", weight = 0.20, type = "items", cols = 1, rows = 1 },
    ["ammobox_snip"] = { label = "Sniper Magazine Box", weight = 0.20, type = "items", cols = 1, rows = 1 },

    ["ammobox_heavy"] = { label = "Heavy Magazine Box", weight = 0.20, type = "items", cols = 1, rows = 1 },
    ["ammobox_rocket"] = { label = "Rocket Ammo Box", weight = 0.20, type = "items", cols = 2, rows = 1 },

    ["ammobox_beambag"] = { label = "Beambag Ammo Box", weight = 0.20, type = "items", cols = 2, rows = 1 },

    ["ammobox_global"] = { label = "Global Magazine Box", weight = 0.20, type = "items", cols = 1, rows = 1 },

    
    -- WEAPON COMPONENTS

    ["components_suppressor"] = { label = "Suppresseur", weight = 0.10, type = "items", cols = 2, rows = 1, notStackable = true },
    ["components_flashlight"] = { label = "Lampe d'arme", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true },
    ["components_grip"] = { label = "Poignée d'arme", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true },
    ["components_weaponskin"] = { label = "Skin d'arme", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true },
    

    

    ["ammo30"] = { label = "Boite de munition (x30)", weight = 0.30, type = "items", cols = 1, rows = 1 },
    ["herse"] = { label = "Herse", weight = 1.00, type = "items", cols = 2, rows = 2 },
    ["boombox"] = { label = "Boombox", weight = 1.50, type = "items", cols = 1, rows = 1},
    ["spray"] = { label = "Bombe de peinture", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["light"] = { label = "Lampe", weight = 1.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_flashlight"] = { label = "Lampe", weight = 1.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_bat"] = { label = "Batte de baseball", weight = 1.00, type = "weapons", cols = 1, rows = 1 },
    ["weapon_bottle"] = { label = "Bouteille cassée", weight = 0.30, type = "weapons", cols = 1, rows = 1 },
    ["weapon_crowbar"] = { label = "Pied de biche", weight = 1.00, type = "weapons", cols = 2, rows = 1 },
    ["weapon_golfclub"] = { label = "Club de golf", weight = 1.00, type = "weapons", 1, rows = 1 },
    ["weapon_hatchet"] = { label = "Hachette", weight = 0.50, type = "weapons", cols = 1, rows = 1 },
    ["weapon_knuckle"] = { label = "Poing américain", weight = 0.50, type = "weapons", cols = 1, rows = 1 },
    ["weapon_machete"] = { label = "Machette", weight = 1.00, type = "weapons", cols = 1, rows = 2 },
    ["weapon_nightstick"] = { label = "Matraque", weight = 1.00, type = "weapons", cols = 1, rows = 2 },
    ["weapon_hammer"] = { label = "Marteau", weight = 1.00, type = "weapons", cols = 1, rows = 2 },
    ["weapon_wrench"] = { label = "Clé anglaise", weight = 1.00, type = "weapons", cols = 1, rows = 2 },
    ["weapon_knife"] = { label = "Couteau", weight = 0.30, type = "weapons", cols = 1, rows = 1 },
    ["weapon_switchblade"] = { label = "Couteau à cran d arrêt", weight = 0.30, type = "weapons", cols = 1, rows = 1 },
    ["weapon_battleaxe"] = { label = "Hache de guerre", weight = 1.00, type = "weapons", cols = 1, rows = 2 },
    ["weapon_poolcue"] = { label = "Queue de billard", weight = 1.00, type = "weapons", cols = 1, rows = 2 },
    ["weapon_grenade"] = { label = "Grenade", weight = 0.20, type = "weapons", cols = 1, rows = 1 },
    ["weapon_bzgas"] = { label = "Gaz BZ", weight = 0.20, type = "weapons", cols = 1, rows = 1 },
    ["weapon_molotov"] = { label = "Cocktail molotov", weight = 0.20, type = "weapons", cols = 1, rows = 1 },
    ["weapon_stickybomb"] = { label = "Bombe collante", weight = 0.20, type = "weapons", cols = 1, rows = 1 },
    ["weapon_poxmine"] = { label = "Mine de proximité", weight = 0.20, type = "weapons", cols = 1, rows = 1 },
    ["weapon_snowball"] = { label = "Boule de neige", weight = 0.10, type = "weapons", cols = 1, rows = 1 },
    ["weapon_ball"] = { label = "Balle de baseball", weight = 0.10, type = "weapons", cols = 1, rows = 1 },
    ["weapon_petrolcan"] = { label = "Bidon d essence", weight = 0.80, type = "weapons", cols = 2, rows = 2 },
    ["weapon_fireextinguisher"] = { label = "Extincteur", weight = 1.00, type = "weapons", cols = 2, rows = 2 },
    ["gadget_parachute"] = { label = "Parachute", weight = 1.00, type = "weapons", cols = 2, rows = 3 },
    ["weapon_dagger"] = { label = "Dague antique", weight = 0.30, type = "weapons", cols = 1, rows = 1 },
    --
    ["weapon_canette"] = { label = "Canette", weight = 0.10, type = "weapons", cols = 1, rows = 1},
    ["weapon_bouteille"] = { label = "Bouteille", weight = 0.10, type = "weapons", cols = 1, rows = 1 },
    ["weapon_pelle"] = { label = "Pelle", weight = 1.00, type = "weapons", cols = 1, rows = 1 },
    ["weapon_pickaxe"] = { label = "Pioche", weight = 1.00, type = "weapons", cols = 1, rows = 1 },
    ["weapon_sledgehammer"] = { label = "Masse", weight = 1.00, type = "weapons", cols = 1, rows = 1 },
    ["weapon_katana"] = { label = "Katana", weight = 1.00, type = "weapons", cols = 1, rows = 1 },
    ["weapon_nailgun"] = { label = "Pistolet à clous", weight = 1.00, type = "weapons", cols = 1, rows = 1 },

    ["weapon_beambag"] = { label = "Beambag", weight = 1.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_smokelspd"] = { label = "Grenade fumigène", weight = 1.00, type = "weapons", cols = 1, rows = 1 },

    ["weapon_fakecombatpistol"] = { label = "Faux pistolet de combat", weight = 1.00, type = "weapons", cols = 2,
        rows = 2 },
    ["weapon_fakesmg"] = { label = "Fausse mitraillette", weight = 1.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_fakeshotgun"] = { label = "Faux fusil à pompe", weight = 1.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_fakeminismg"] = { label = "Fausse mitraillette légère", weight = 1.00, type = "weapons", cols = 2,
        rows = 2 },
    ["weapon_fakemicrosmg"] = { label = "Faux pistolet mitrailleur", weight = 1.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_fakeak"] = { label = "Faux fusil d assaut", weight = 1.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_fakeaku"] = { label = "Faux fusil d assaut compact", weight = 1.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_fakem4"] = { label = "Fausse carabine", weight = 1.00, type = "weapons", cols = 3, rows = 2 },
    -- add weapon_fakepistol, WEAPON_FAKEMACHINEPISTOL, WEAPON_FAKESPECIALCARBINE
    ["weapon_fakepistol"] = { label = "Faux pistolet", weight = 1.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_fakemachinepistol"] = { label = "Faux pistolet mitrailleur", weight = 1.00, type = "weapons", cols = 2,
        rows = 2 },
    ["weapon_fakespecialcarbine"] = { label = "Faux fusil d assaut spécial", weight = 1.00, type = "weapons", cols = 3,
        rows = 2 },

    ["weapon_pistol"] = { label = "Beretta 92 FS", weight = 2.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_combatpistol"] = { label = "Glock 17", weight = 2.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_pistol50"] = { label = "Desert Eagle .50", weight = 2.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_snspistol"] = { label = "H&K P7M10", weight = 1.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_heavypistol"] = { label = "Colt M45A1", weight = 2.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_flaregun"] = { label = "Pistolet de détresse", weight = 1.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_stungun_mp"] = { label = "Coil X26P", weight = 1.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_revolver"] = { label = "Taurus Raging Bull", weight = 2.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_vintagepistol"] = { label = "FN Model 1922", weight = 2.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_doubleaction"] = { label = "Colt M1892", weight = 2.00, type = "weapons", cols = 2, rows = 2 },

    ["weapon_microsmg"] = { label = "IMI UZI", weight = 3.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_machinepistol"] = { label = "Intratec TEC-DC9", weight = 3.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_minismg"] = { label = "Škorpion Vz. 61", weight = 3.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_smg"] = { label = "H&K MP5A5", weight = 3.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_gusenberg"] = { label = "M1928A1 Thompson", weight = 3.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_assaultrifle"] = { label = "AK-47", weight = 4.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_carbinerifle"] = { label = "M4A1", weight = 4.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_specialcarbine"] = { label = "H&K G36C", weight = 4.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_pumpshotgun"] = { label = "Remington 870E", weight = 3.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_sawnoffshotgun"] = { label = "Mossberg 500", weight = 3.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_assaultshotgun"] = { label = "UTAS UTS-15", weight = 3.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_musket"] = { label = "Mousquet", weight = 3.00, type = "weapons", cols = 4, rows = 2 },
    ["weapon_heavyshotgun"] = { label = "Saiga 12K", weight = 3.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_dbshotgun"] = { label = "Double Canon", weight = 3.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_compactrifle"] = { label = "AKS-74u", weight = 4.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_combatshotgun"] = { label = "Franchi SPAS-12", weight = 4.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_autoshotgun"] = { label = "Armsel Striker", weight = 3.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_laser"] = { label = "Fusil de laser game", weight = 2.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_paintball"] = { label = "Fusil de paintball", weight = 2.00, type = "weapons", cols = 2, rows = 2 },
    ["weapon_flare"] = { label = "Fusée de détresse", weight = 0.30, type = "weapons", cols = 3, rows = 2 },
    ["weapon_firework"] = { label = "Lanceur pyrotechnique", weight = 4.00, type = "weapons", cols = 3, rows = 2 },
    ["weapon_sniperrifle"] = { label = "Fusil L96A1", weight = 8.00, type = "weapons", cols = 4, rows = 2 },
    
    -- add lapin, orc, requin, coyote, sanglier, biche, puma and oiseau
    ["lapin"] = { label = "Viande de lapin", weight = 1.00, type = "items", cols = 1, rows = 1 },
    ["orc_v"] = { label = "Viande d'orque", weight = 1.00, type = "items", cols = 1, rows = 1 },
    ["requin_v"] = { label = "Viande de requin", weight = 1.00, type = "items", cols = 1, rows = 1 },
    ["coyote"] = { label = "Viande de coyote", weight = 1.00, type = "items", cols = 1, rows = 1 },
    ["sanglier"] = { label = "Viande de sanglier", weight = 1.00, type = "items", cols = 1, rows = 1 },
    ["biche"] = { label = "Viande de biche", weight = 1.00, type = "items", cols = 1, rows = 1 },
    ["puma"] = { label = "Viande de puma", weight = 1.00, type = "items", cols = 1, rows = 1 },
    ["oiseau"] = { label = "Viande d'oiseau", weight = 1.00, type = "items", cols = 1, rows = 1 },
    ["cleaner"] = { label = "Produit nettoyant", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["sangle"] = { label = "Sangle", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["tunertablet"] = { label = "Tablette de tuning", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["shield"] = { label = "Bouclier balistique", weight = 3.00, type = "items", cols = 2, rows = 2 },
    ["lssdshield"] = { label = "Bouclier balistique", weight = 3.00, type = "items", cols = 2, rows = 2 },
    
    -- event
    ["liasse"] = { label = "Livres égyptiens", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["collier2"] = { label = "Collier de la reine", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["sicacoin"] = { label = "Sicacoin", weight = 0.10, type = "items", cols = 1, rows = 1 },

    -- Seller items (5N)
    ["serflex"] = { label = "Zip Ties", weight = 0.10, type = "items", cols = 1, rows = 1},
    ["sactete"] = { label = "Sac tête", weight = 0.10, type = "items", cols = 1, rows = 1},
    ["pincecoupante"] = { label = "Pince coupante", weight = 0.10, type = "items", cols = 1, rows = 1},

    -- Noel
    ["barbeapapa"] = { label = "Barbe à Papa", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["boulenoel"] = { label = "Boule de Noël", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["cafeaulait"] = { label = "Café au lait", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["chocolatchaud"] = { label = "Chocolat Chaud", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["churros"] = { label = "Churros", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["crepe"] = { label = "Crêpe", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["donut"] = { label = "Donuts", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["gauffre"] = { label = "Gauffre", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["guirlande"] = { label = "Guirlande", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["guirlande2"] = { label = "Guirlande électrique", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["pommeamour"] = { label = "Pomme d'amour", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["sapin"] = { label = "Sapin", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["sucreorge"] = { label = "Sucre d'orge", weight = 0.10, type = "items", cols = 1, rows = 1 },

    --farm 
    ["letter"] = { label = "Lettre", weight = 0.10, type = "items", cols = 1, rows = 1,},
    ["chainsaw"] = { label = "Tronçonneuse", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true},
    ["rawwood"] = { label = "Bois brut", weight = 1.0, type = "items", cols = 1, rows = 1},
    ["axe"] = { label = "Pioche", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true},
    ["iron"] = { label = "Minerai de fer", weight = 3, type = "items", cols = 1, rows = 1},
    ["gold"] = { label = "Minerai d'or", weight = 3, type = "items", cols = 1, rows = 1},
    ["charcoal"] = { label = "Minerai de charbon", weight = 3, type = "items", cols = 1, rows = 1},
    ["shears"] = { label = "Sécateur", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true},
    ["grape"] = { label = "Grappe de raisin", weight = 0.10, type = "items", cols = 1, rows = 1},

    -- Event
    ["chandelier"] = { label = "Menorah", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["toupie"] = { label = "Toupie", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["firework"] = { label = "Feux d'artifice", weight = 0.10, type = "items", cols = 1, rows = 1 },

    --ltd
    ["gum"] = { label = "Chewing gum", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["lollipop"] = { label = "Sucette", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["cigar"] = { label = "Cigar", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["scissors"] = { label = "Ciseaux", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["Mr"] = { label = "Mr freeze", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["jumelles"] = { label = "Jumelles", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["cake"] = { label = "Gateau", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["fishroad"] = { label = "Canne à pêche", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["ticket"] = { label = "Ticket à gratter", weight = 0.10, type = "items", cols = 1, rows = 1 },
    
    ["popcorn"] = { label = "PopCorn", weight = 0.10, type = "items", cols = 1, rows = 1 },

    ["tickettombola"] = { label = "Ticket Tombola", weight = 0.10, type = "items", cols = 1, rows = 1 },

    ["triangle"] = { label = "Sandwich Triangle", weight = 0.10, type = "items", cols = 1, rows = 1 },
    
    ["Chips"] = { label = "Chips", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["GlaceItalienne"] = { label = "Glace a l'italienne", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["BarreCereale"] = { label = "Barre de Cereale", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["eaupetillante"] = { label = "Eau Petillante", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["laitchoco"] = { label = "Lait au Chocolat", weight = 0.10, type = "items", cols = 1, rows = 1 },

    ["cofeecup"] = { label = "cup de cafée", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["chocolatbar"] = { label = "barre de cereale", weight = 0.10, type = "items", cols = 1, rows = 1 },

    --g6
    ["sacargent"] = { label = "sac d'argent", weight = 0.10, type = "items", cols = 1, rows = 1 },

    --lspd
    ["lspdgiletj"] = { label = "LSPD - Gilet Jaune", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lspdkevle1"] = { label = "LSPD - Leger 1", weight = 0.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lspdkevle2"] = { label = "LSPD - Leger 2", weight = 0.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lspdkevle3"] = { label = "LSPD - Leger 3", weight = 0.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lspdriot"] = { label = "LSPD - Riot", weight = 1.50, type = "items", cols = 1, rows = 1,notStackable = true },
    ["lspdkevm1"] = { label = "LSPD - Moyen", weight = 1, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lspdkevlo1"] = { label = "LSPD - Lourd 1", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lspdkevlo2"] = { label = "LSPD - Lourd 2", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lspdkevlo3"] = { label = "LSPD - Lourd 3", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lspdswat"] = { label = "LSPD - SWAT", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lspdkevpc"] = { label = "LSPD - Pare Couteau", weight = 0.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lspdgnd"] = { label = "LSPD - GND", weight = 0.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lspdgnd2"] = { label = "LSPD - GND Lourd", weight = 0.50, type = "items", cols = 1, rows = 1, notStackable = true },

    --usss
    ["insigneKevUsss"] = { label = "USSS - Insigne", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true },
    ["ussskev1"] = { label = "USSS - Kevlar 1", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["ussskev2"] = { label = "USSS - Kevlar 2", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["ussskev3"] = { label = "USSS - Kevlar 3", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["ussskev4"] = { label = "USSS - Léger 1", weight = 0.50, type = "items", cols = 1, rows = 1, notStackable = true },

    --lssd
    ["lssdgiletj"] = { label = "LSSD - Gilet Jaune", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lssdkevle1"] = { label = "LSSD - Léger 1", weight = 0.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lssdkevle2"] = { label = "LSSD - Pare-Couteau", weight = 0.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lssdkevlo1"] = { label = "LSSD - Kevlar 1", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lssdkevlo2"] = { label = "LSSD - Kevlar 2", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lssdkevlo3"] = { label = "LSSD - Kevlar 3", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lssdkevlo4"] = { label = "LSSD - Kevlar 4", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lssdkevlo5"] = { label = "LSSD - Kevlar 5", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lssdkevlo6"] = { label = "LSSD - Kevlar 6", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lssdkevlo7"] = { label = "LSSD - Kevlar 7", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lssdinsigne"] = { label = "LSSD - Insigne", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true },
    ["lssdriot"] = { label = "LSSD - Riot", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },

    --USBP
    ["usbpkevlo1"] = { label = "USPB - Lourd 1", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["usbpkevlo2"] = { label = "USPB - Lourd 2", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["usbpkevlo3"] = { label = "USPB - Lourd 3", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["usbpkevlo4"] = { label = "USPB - Lourd 4", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["usbpkevlo5"] = { label = "USPB - Lourd 5", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["usbpkevpc"] = { label = "USPB - Pare Couteau", weight = 0.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["usbpgiletb"] = { label = "USPB - Gilet Bateau", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true },
    ["usbpgiletj"] = { label = "USPB - Gilet Jaune", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true },
    ["usbpinsigne"] = { label = "USPB - Insigne", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true },

    --DOJ & Gov
    ["dojkev"] = { label = "DOJ - Kevlar", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true },
    ["govbadge"] = { label = "Badge Gouvernement", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true },

    --BOI
    ["boikev"] = { label = "BOI - Kevlar", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true },

    --sams
    ["samskev"] = { label = "Medic - Kevlar", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },

    --weazel
    ["wzkev"] = { label = "Weazel - Kevlar", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },

    --gpb illégal
    ["keville1"] = { label = "Kevlar Léger 1", weight = 0.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["keville2"] = { label = "Kevlar Léger 2", weight = 0.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["keville3"] = { label = "Kevlar Léger 3", weight = 0.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["keville4"] = { label = "Kevlar Léger 4", weight = 0.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["keville5"] = { label = "Kevlar Lourd 1", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["keville6"] = { label = "Kevlar Lourd 2", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["keville7"] = { label = "Kevlar Lourd 3", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["keville8"] = { label = "Kevlar Lourd 4", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["keville9"] = { label = "Kevlar Moyen 1", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["keville10"] = { label = "Kevlar Moyen 2", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["keville11"] = { label = "Kevlar Moyen 3", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["keville12"] = { label = "Kevlar Moyen 4", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },
    ["giletc4"] = { label = "Veste Explosive", weight = 1.50, type = "items", cols = 1, rows = 1, notStackable = true },

    --Le Miroir
    ["steak"] = { label = "Entrecote", weight = 0.10, type = "items", cols = 1, rows = 1 },

    ["caviar"] = { label = "Caviar", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["magret"] = { label = "Magret", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["foiegras"] = { label = "Foie Gras", weight = 0.10, type = "items", cols = 1, rows = 1 },


    ["citronade"] = { label = "Limonade", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["glace"] = { label = "Glaces", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["chocolateCake"] = { label = "Fondant au chocolat", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["crabe"] = { label = "Fruits de Mer", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["mouleFrite"] = { label = "Moules Frite", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["steakChelou"] = { label = "Pain de viande", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["donnut"] = { label = "Donnut sucré au sucre", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["recycleur"] = { label = "Recycleur", weight = 0.10, type = "items", cols = 1, rows = 1 },

    ["papier"] = { label = "Papier", weight = 0.01, type = "items", cols = 1, rows = 1, notStackable = true },
    ["blocnote"] = { label = "Bloc note", weight = 0.01, type = "items", cols = 1, rows = 1, notStackable = true },
    --new Item restraurant

    --burgershot
    ["thesimplyburger"] = { label = "Burger Simple", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["chickenwrap"] = { label = "Wrap Poulet", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["goatcheesewrap"] = { label = "Wrap Chèvre", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["friesbox"] = { label = "Frites", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["thefabulous6lbburger"] = { label = "Fabulous Burger", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["thegloriousburger"] = { label = "Cheeseburger", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["doubleshotburger"] = { label = "Double Cheese", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["bssoda"] = { label = "Soda", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["meteoriteicecream"] = { label = "Meteorite Ice Cream", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["orangotangicecream"] = { label = "Orangotang Ice Cream", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["pricklyburger"] = { label = "Prickly Burger", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["bleederburger"] = { label = "Bleeder Burger", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},


    -- uwu
    ["BarbaMilk"] = { label = "BarbaMilk", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70 },
    ["BubbleTea"] = { label = "Bubble Tea", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["CatPat"] = { label = "CatPat", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["ChatGourmand"] = { label = "Chat Gourmand", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Chatmallow"] = { label = "Chatmallow", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["IceCoffee"] = { label = "Ice Coffee", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["IceCreamCat"] = { label = "IceCream Cat", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Lailaitchaud"] = { label = "Lailait chaud", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Milkshake"] = { label = "Milkshake", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Mochi"] = { label = "Mochi", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Pocky"] = { label = "Pocky", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["UwUBurger"] = { label = "UwU Burger", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},

    ["LatteMatcha"] = { label = "Latte Matcha", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Sushis"] = { label = "Sushis", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Ramens"] = { label = "Ramens", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    
    ["melto"] = { label = "Melto", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["lapinut"] = { label = "Lapinut", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},

    --unicorn
    ["Aperitifs"] = { label = "Aperitifs", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["CoolGranny"] = { label = "Cool Granny", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Doudou"] = { label = "Doudou", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["FrenchKiss"] = { label = "French Kiss", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["RedVelvet"] = { label = "Red Velvet", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Sexonthebeach"] = { label = "Sex on the beach", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Unitail"] = { label = "Uni tail", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Limonade"] = { label = "Limonade", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Jusdefruits"] = { label = "Jus de fruits", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Soda"] = { label = "Soda", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    --bm
    ["Cafefrappe"] = { label = "Cafe frappé", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 50},
    ["Cafepraline"] = { label = "Cafe praliné", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 50},
    ["Cappuccino"] = { label = "Cappuccino", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 50},
    ["Caramelmacchiato"] = { label = "Caramel macchiato", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Chocoguimauve"] = { label = "Choco guimauve", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Chocolatviennois"] = { label = "Chocolat viennois", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Cookie"] = { label = "Cookie", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Expresso"] = { label = "Expresso", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Latte"] = { label = "Latte", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Muffinchoco"] = { label = "Muffin choco", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 50},
    ["Theglace"] = { label = "Thé glacé", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},

    ["CinnamonRolls"] = { label = "Cinnamon Rolls", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Cheesecake"] = { label = "Cheesecake", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},

    ["dynamite"] = {label = "Dynamite", weight = 0.5, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},

    --miroir
    ["Fondantchocolat"] = { label = "Fondant chocolat", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Waffle"] = { label = "Gaufre", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Moulesfrites"] = { label = "Moules frites", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Plateaudecharcuterie"] = { label = "Plateau de charcuterie", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["escalope"] = { label = "Escalope", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["seafood-in-wood-"] = { label = "Plateau des mers", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Americanribs"] = { label = "American ribs", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["champagne"] = { label = "Champagne", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Vinblanc"] = { label = "Vin blanc", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Vinrouge"] = { label = "Vin rouge", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    --cluckin
    ["gncluckinbucket"] = { label = "Buckets", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["gncluckinburg"] = { label = "Burger", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["gncluckinfowl"] = { label = "Volaille à croquer", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["gncluckinfries"] = { label = "Frites", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["gncluckinkids"] = { label = "Menu Enfant", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["gncluckinrings"] = { label = "Onion Rings", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["gncluckinsalad"] = { label = "Salade", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["gncluckinsoup"] = { label = "Soupe", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["gncluckincup"] = { label = "Soda", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    --bahamas
    ["BloodyMary"] = { label = "Bloody Mary", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Blue-Mamas"] = { label = "Blue-Mamas", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Gin"] = { label = "Gin", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Mojito"] = { label = "Mojito", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Punch"] = { label = "Punch", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["WhiteLady"] = { label = "White Lady", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Tapas"] = { label = "Tapas", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    --bl
    ["Bretzel"] = { label = "Bretzel", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Poutine"] = { label = "Poutine", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Saucisson"] = { label = "Saucisson", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["vinchaud"] = { label = "vin chaud", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Blonde"] = { label = "Bière Blonde", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},

    ["Entrecote"] = { label = "Entrecôte", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["OeufsBacon"] = { label = "Oeufs bacon", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},

    ["Mac&cheese"] = { label = "Mac & cheese", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},

    ["Applepie"] = { label = "Apple pie", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 50},

    ["DuffBeer"] = { label = "Duff Beer", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["BayviewBeer"] = { label = "Bayview Beer", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},


    --comrades
    ["Camarade"] = { label = "Camarade", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Jaggerbomb"] = { label = "Jaggerbomb", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Vodka"] = { label = "Vodka", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Whisky"] = { label = "Whisky", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    --pops
    ["911"] = { label = "911", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Cesar"] = { label = "Cesar", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Hotdog"] = { label = "Hot dog", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Mozzasticks"] = { label = "Mozza sticks", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Pancakes"] = { label = "Pancakes", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["pizza-7945"] = { label = "pizza", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["PulledPork"] = { label = "Pulled Pork", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Sandwich"] = { label = "Sandwich", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    --yellowjack
    ["Brune"] = { label = "Bière Brune", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Rousse"] = { label = "Bière Rousse", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Ambree"] = { label = "Bière Ambree", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Pissedane"] = { label = "Pisse d\'Âne", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Shamrock"] = { label = "Shamrock", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},

    ["WilliamPeel"] = { label = "William Peel", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["RhumCoke"] = { label = "Rhum Coke", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},

    ["drugsBags"] = { label = "Sacs de Drogues", weight = 5.00, type = "items", cols = 1, rows = 1 },

    -- coke
    ["eaudechaux"] = { label = "Eau de chaux", weight = 0.1, type = "items", cols = 1, rows = 1 },
    ["feuilledecoca"] = { label = "Feuille de coca", weight = 0.01, type = "items", cols = 1, rows = 1 },
    ["acidesulfurique"] = { label = "Acide sulfurique", weight = 0.01, type = "items", cols = 1, rows = 1 },
    ["kerosene"] = { label = "Kerosene", weight = 0.01, type = "items", cols = 1, rows = 1 },
    
    -- weed
    ["fertilisant"] = { label = "Fertilisant", weight = 0.01, type = "items", cols = 1, rows = 1 },
    ["grainecannabis"] = { label = "Graines de cannabis", weight = 0.01, type = "items", cols = 1, rows = 1 },
    ["engrais"] = { label = "Engrais", weight = 0.01, type = "items", cols = 1, rows = 1 },
    ["feuilledeweed"] = { label = "Feuille de weed", weight = 0.1, type = "items", cols = 1, rows = 1 },

    -- meth
    ["ephedrine"] = { label = "Ephedrine", weight = 0.01, type = "items", cols = 1, rows = 1 },
    ["methylamine"] = { label = "Methylamine", weight = 0.01, type = "items", cols = 1, rows = 1 },
    ["phenylacetone"] = { label = "Phenylacetone", weight = 0.01, type = "items", cols = 1, rows = 1 },

    -- heroine
    ["pavosomnifere"] = { label = "Pavo somnifère", weight = 0.01, type = "items", cols = 1, rows = 1 },
    ["chlorureammonium"] = { label = "Chlorure Ammonium", weight = 0.01, type = "items", cols = 1, rows = 1 },
    ["anhydrideacetique"] = { label = "Anhydride Acétique", weight = 0.01, type = "items", cols = 1, rows = 1 },

    -- DISQUE

    ["disquediamant"] = { label = "Disque de Diamant", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["disqueor"] = { label = "Disque d'Or", weight = 0.15, type = "items", cols = 1, rows = 1 },
    ["disqueplatine"] = { label = "Disque de Platine", weight = 0.20, type = "items", cols = 1, rows = 1 },

    -- NEW ITEMS

    ["malettecuir"] = { label = "Malette en Cuir", weight = 0.10, type = "items", cols = 1, rows = 1 },

    ["twinkies"] = { label = "Twinkies", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 35},

    -- Bayview

    ["Hydromel"] = { label = "Hydromel", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},

    -- golf
    ["golfb"] = { label = "Balle de golf blanche", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["golfj"] = { label = "Balle de golf jaune", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["golfv"] = { label = "Balle de golf verte", weight = 0.10, type = "items", cols = 1, rows = 1 },
    ["golfr"] = { label = "Balle de golf rose", weight = 0.10, type = "items", cols = 1, rows = 1 },

    -- tasergame
    ["tasertrophy1"] = { label = "Trophée Taser Game", weight = 1.0, type = "items", cols = 1, rows = 1 },

    -- Ice Cream
    ["3ballsicecream"] = { label = "Glace 3 Boules", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["pistacheicecream"] = { label = "Glace Pistache", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["chocolateicecream"] = { label = "Glace Chocolat", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["vanilaicecream"] = { label = "Glace Vanille", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["misterfreeze"] = { label = "Mister Freeze", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["granita"] = { label = "Granita", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["strawberryicecream"] = { label = "Glace Fraise", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["magnumicecream"] = { label = "Glace Magnum", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["ben&jerrys"] = { label = "Ben & Jerry's", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},

    ["keys"] = { label = "clé", weight = 0.10, type = "items", cols = 1, rows = 1, notStackable = true },

    --pizzeria
    ["pizzaburata"] = { label = "Pizza Burata", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["pizzamarghe"] = { label = "Pizza Margherita", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["pizza4fromage"] = { label = "Pizza 4 Fromages", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["pizzachevre"] = { label = "Pizza Chèvre Miel", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["crostini"] = { label = "Crostini", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["saladeburata"] = { label = "Salade Burata", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["pizzanutella"] = { label = "Pizza Nutella", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["saladeburata"] = { label = "Salade Burata", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["saladedefruit"] = { label = "Salade de Fruits", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    

    -- pearl
    ["Cocktail"] = { label = "Cocktail", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Crevettes"] = { label = "Crevettes", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["FishBowl"] = { label = "FishBowl", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Huitres"] = { label = "Huitres", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Moules"] = { label = "Moules", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Tarte_au_Citron"] = { label = "Tarte au Citron", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},

    -- upnatom
    ["Black_burger"] = { label = "Black Burger", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Burger_earth"] = { label = "Earth Burger", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Burger_Uranus"] = { label = "Saturne Burger", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Cup_space"] = { label = "Cup Space", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Eggs_muffin"] = { label = "Eggs Muffin", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Frites_zigzag"] = { label = "Frites Zigzag", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Granita_upnatom"] = { label = "Granita", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Ice_cup"] = { label = "Ice Cup", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Onion_rings"] = { label = "Onion Rings", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},

    -- hornys
    ["Batonspoulet_Hornys"] = { label = "Baton de Poulet", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Burgerpoulet_Hornys"] = { label = "Burger de Poulet", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Donut_Hornys"] = { label = "Donus", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Frites_Hornys"] = { label = "Frites", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Milkshake_Hornys"] = { label = "Milkshake", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Pignonpoulet_Hornys"] = { label = "Pignon de Poulet", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Wrappoulet_Hornys"] = { label = "Wrap Poulet", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'food', number = 70},
    ["Coffee_Hornys"] = { label = "Café", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
    ["Soda_Hornys"] = { label = "Soda", weight = 0.1, type = "items", cols = 1, rows = 1, foodType = 'drink', number = 70},
}

items.maxWeight = 25.0
