Custom = {

    perf = {
        --Moteur
        { name = "Moteur", label = 11 },
        { name = "Frein", label = 12 },
        { name = "Transmission", label = 13 },
        { name = "Suspension", label = 15 },
        { name = "Turbo", label = 18 },

    },
    horn = {},
    color = {
        { name = "Normal", label = 0, color = {
            { id = 1, name = "Noir carbone" },
            { id = 2, name = "Graphite" },
            { id = 3, name = "Anthracite" },
            { id = 4, name = "Acier noir" },
            { id = 5, name = "Acier foncé" },
            { id = 6, name = "Argent" },
            { id = 7, name = "Argent bleuté" },
            { id = 8, name = "Acier laminé" },
            { id = 9, name = "Argent sombre" },
            { id = 10, name = "Argent pierre" },
            { id = 11, name = "Argent nocturne" },
            { id = 12, name = "Argent béton" },
            { id = 13, name = "Rouge" },
            { id = 14, name = "Rouge Torino" },
            { id = 15, name = "Rouge Formula" },
            { id = 16, name = "Rouge lave" },
            { id = 17, name = "Rouge flamme" },
            { id = 18, name = "Rouge gracieux" },
            { id = 19, name = "Rouge grenat" },
            { id = 20, name = "Rouge solaire" },
            { id = 21, name = "Rouge cabernet" },
            { id = 22, name = "Rouge sang" },
            { id = 23, name = "Rouge fraise" },
            { id = 24, name = "Rose vif" },
            { id = 25, name = "Rose Pfister" },
            { id = 26, name = "Saumon" },
            { id = 27, name = "Orange profond" },
            { id = 28, name = "Orange" },
            { id = 29, name = "Orange vif" },
            { id = 30, name = "Or" },
            { id = 31, name = "Bronze" },
            { id = 32, name = "Jaune" },
            { id = 33, name = "Jaune racing" },
            { id = 34, name = "Jaune pâle" },
            { id = 35, name = "Vert foncé" },
            { id = 36, name = "Vert racing" },
            { id = 37, name = "Vert marin" },
            { id = 38, name = "Vert olive" },
            { id = 39, name = "Vert clair" },
            { id = 40, name = "Vert pétrole" },
            { id = 41, name = "Vert lime" },
            { id = 42, name = "Bleu nocturne" },
            { id = 43, name = "Bleu galaxie" },
            { id = 44, name = "Bleu foncé" },
            { id = 45, name = "Bleu cobalt" },
            { id = 46, name = "Bleu" },
            { id = 47, name = "Bleu ciel" },
            { id = 48, name = "Bleu ardoise" },
            { id = 49, name = "Bleu diamant" },
            { id = 50, name = "Bleu écume" },
            { id = 51, name = "Bleu nautique" },
            { id = 52, name = "Bleu racing" },
            { id = 53, name = "Bleu ultra" },
            { id = 54, name = "Bleu clair" },
            { id = 55, name = "Chocolat" },
            { id = 56, name = "Brun bison" },
            { id = 57, name = "Brun beige" },
            { id = 58, name = "Brun Feltzer" },
            { id = 59, name = "Brun érable" },
            { id = 60, name = "Brun cannelle" },
            { id = 61, name = "Terre de sienne" },
            { id = 62, name = "Beige" },
            { id = 63, name = "Brun vert" },
            { id = 64, name = "Brun hêtre" },
            { id = 65, name = "Brun paille" },
            { id = 66, name = "Brun sable" },
            { id = 67, name = "Beige clair" },
            { id = 68, name = "Mauve Schafter" },
            { id = 69, name = "Mauve Spinnaker" },
            { id = 70, name = "Mauve nocturne" },
            { id = 71, name = "Violet" },
            { id = 72, name = "Crème" },
            { id = 73, name = "Blanc glacier" },
            { id = 74, name = "Blanc givre" }
        } },
        { name = "Métallique", label = 1, color = {
            { name = "Noir carbone", id = 1 },
            { name = "Graphite", id = 2 },
            { name = "Anthracite", id = 3 },
            { name = "Acier noir", id = 4 },
            { name = "Acier foncé", id = 5 },
            { name = "Argent", id = 6 },
            { name = "Argent bleuté", id = 7 },
            { name = "Acier laminé", id = 8 },
            { name = "Argent sombre", id = 9 },
            { name = "Argent pierre", id = 10 },
            { name = "Argent nocturne", id = 11 },
            { name = "Argent béton", id = 12 },
            { name = "Rouge", id = 13 },
            { name = "Rouge Torino", id = 14 },
            { name = "Rouge Formula", id = 15 },
            { name = "Rouge lave", id = 16 },
            { name = "Rouge flamme", id = 17 },
            { name = "Rouge gracieux", id = 18 },
            { name = "Rouge grenat", id = 19 },
            { name = "Rouge solaire", id = 20 },
            { name = "Rouge cabernet", id = 21 },
            { name = "Rouge sang", id = 22 },
            { name = "Rouge fraise", id = 23 },
            { name = "Rose vif", id = 24 },
            { name = "Rose Pfister", id = 25 },
            { name = "Saumon", id = 26 },
            { name = "Orange profond", id = 27 },
            { name = "Orange", id = 28 },
            { name = "Orange vif", id = 29 },
            { name = "Or", id = 30 },
            { name = "Bronze", id = 31 },
            { name = "Jaune", id = 32 },
            { name = "Jaune racing", id = 33 },
            { name = "Jaune pâle", id = 34 },
            { name = "Vert foncé", id = 35 },
            { name = "Vert racing", id = 36 },
            { name = "Vert marin", id = 37 },
            { name = "Vert olive", id = 38 },
            { name = "Vert clair", id = 39 },
            { name = "Vert pétrole", id = 40 },
            { name = "Vert lime", id = 41 },
            { name = "Bleu nocturne", id = 42 },
            { name = "Bleu galaxie", id = 43 },
            { name = "Bleu foncé", id = 44 },
            { name = "Bleu cobalt", id = 45 },
            { name = "Bleu", id = 46 },
            { name = "Bleu ciel", id = 47 },
            { name = "Bleu ardoise", id = 48 },
            { name = "Bleu diamant", id = 49 },
            { name = "Bleu écume", id = 50 },
            { name = "Bleu nautique", id = 51 },
            { name = "Bleu racing", id = 52 },
            { name = "Bleu ultra", id = 53 },
            { name = "Bleu clair", id = 54 },
            { name = "Chocolat", id = 55 },
            { name = "Brun bison", id = 56 },
            { name = "Brun beige", id = 57 },
            { name = "Brun Feltzer", id = 58 },
            { name = "Brun érable", id = 59 },
            { name = "Brun cannelle", id = 60 },
            { name = "Terre de sienne", id = 61 },
            { name = "Beige", id = 62 },
            { name = "Brun vert", id = 63 },
            { name = "Brun hêtre", id = 64 },
            { name = "Brun paille", id = 65 },
            { name = "Brun sable", id = 66 },
            { name = "Beige clair", id = 67 },
            { name = "Mauve Schafter", id = 68 },
            { name = "Mauve Spinnaker", id = 69 },
            { name = "Mauve nocturne", id = 70 },
            { name = "Violet", id = 71 },
            { name = "Crème", id = 72 },
            { name = "Blanc glacier", id = 73 },
            { name = "Blanc givre", id = 74 },
        } },
        { name = "Pearl", label = 2, color = {
            { id = 1, name = "Graphite" },
            { id = 2, name = "Anthracite" },
            { id = 3, name = "Acier noir" },
            { id = 4, name = "Acier foncé" },
            { id = 5, name = "Argent" },
            { id = 6, name = "Argent bleuté" },
            { id = 7, name = "Acier laminé" },
            { id = 8, name = "Argent sombre" },
            { id = 9, name = "Argent pierre" },
            { id = 10, name = "Argent nocturne" },
            { id = 11, name = "Argent béton" },
            { id = 12, name = "Rouge" },
            { id = 13, name = "Rouge Torino" },
            { id = 14, name = "Rouge Formula" },
            { id = 15, name = "Rouge lave" },
            { id = 16, name = "Rouge flamme" },
            { id = 17, name = "Rouge gracieux" },
            { id = 18, name = "Rouge grenat" },
            { id = 19, name = "Rouge solaire" },
            { id = 20, name = "Rouge cabernet" },
            { id = 21, name = "Rouge sang" },
            { id = 22, name = "Rouge fraise" },
            { id = 23, name = "Rose vif" },
            { id = 24, name = "Rose Pfister" },
            { id = 25, name = "Saumon" },
            { id = 26, name = "Orange profond" },
            { id = 27, name = "Orange" },
            { id = 28, name = "Orange vif" },
            { id = 29, name = "Or" },
            { id = 30, name = "Bronze" },
            { id = 31, name = "Jaune" },
            { id = 32, name = "Jaune racing" },
            { id = 33, name = "Jaune pâle" },
            { id = 34, name = "Vert foncé" },
            { id = 35, name = "Vert racing" },
            { id = 36, name = "Vert marin" },
            { id = 37, name = "Vert olive" },
            { id = 38, name = "Vert clair" },
            { id = 39, name = "Vert pétrole" },
            { id = 40, name = "Vert lime" },
            { id = 41, name = "Bleu nocturne" },
            { id = 42, name = "Bleu galaxie" },
            { id = 43, name = "Bleu foncé" },
            { id = 44, name = "Bleu cobalt" },
            { id = 45, name = "Bleu" },
            { id = 46, name = "Bleu ciel" },
            { id = 47, name = "Bleu ardoise" },
            { id = 48, name = "Bleu diamant" },
            { id = 49, name = "Bleu écume" },
            { id = 50, name = "Bleu nautique" },
            { id = 51, name = "Bleu racing" },
            { id = 52, name = "Bleu ultra" },
            { id = 53, name = "Bleu clair" },
            { id = 54, name = "Chocolat" },
            { id = 55, name = "Brun bison" },
            { id = 56, name = "Brun beige" },
            { id = 57, name = "Brun Feltzer" },
            { id = 58, name = "Brun érable" },
            { id = 59, name = "Brun cannelle" },
            { id = 60, name = "Terre de sienne" },
            { id = 61, name = "Beige" },
            { id = 62, name = "Brun vert" },
            { id = 63, name = "Brun hêtre" },
            { id = 64, name = "Brun paille" },
            { id = 65, name = "Brun sable" },
            { id = 66, name = "Beige clair" },
            { id = 67, name = "Mauve Schafter" },
            { id = 68, name = "Mauve Spinnaker" },
            { id = 69, name = "Mauve nocturne" },
            { id = 70, name = "Violet" },
            { id = 71, name = "Crème" },
            { id = 72, name = "Blanc glacier" },
            { id = 73, name = "Blanc givre" }
        } },
        { name = "Matte", label = 3, color = {
            { name = "Gris", id = 1 },
            { name = "Gris clair", id = 2 },
            { name = "Blanc glacier", id = 3 },
            { name = "Bleu", id = 4 },
            { name = "Bleu foncé", id = 5 },
            { name = "Bleu nocturne", id = 6 },
            { name = "Mauve nocturne", id = 7 },
            { name = "Mauve Schafter", id = 8 },
            { name = "Rouge", id = 9 },
            { name = "Rouge foncé", id = 10 },
            { name = "Orange", id = 11 },
            { name = "Jaune", id = 12 },
            { name = "Vert lime", id = 13 },
            { name = "Vert", id = 14 },
            { name = "Vert forêt", id = 15 },
            { name = "Vert feuillage", id = 16 },
            { name = "Vert olive", id = 17 },
            { name = "Terre sombre", id = 18 },
            { name = "Sable du désert", id = 19 }
        } },
        { name = "Metal", label = 4, color = {
            { id = 1, name = "Acier noir brossé" },
            { id = 2, name = "Aluminium brossé" },
            { id = 3, name = "Or pur" },
            { id = 4, name = "Or brossé" }
        } },
        { name = "Chrome", label = 5 },
    },

    wheels = {
        { name = "Haut de gamme", id = 7 },
        { name = "Sport ", id = 0 },
        { name = "Muscle car ", id = 1 },
        { name = "Lowrider", id = 2 },
        { name = "SUV", id = 3 },
        { name = "Offroad", id = 4 },
        { name = "Tuning", id = 5 },
        { name = "Bike", id = 6 },
        { name = "Benny's Original", id = 8 },
        { name = "Benny's Bespoke", id = 9 },
        { name = "OpenWheel", id = 10 },
        { name = "De rue", id = 11 },
        { name = "Circuit", id = 12 },
    },

    windowTint = {
        { name = "Aucune", id = 0 },
        { name = "Noir Pur", id = 1 },
        { name = "Fumée Foncée", id = 2 },
        { name = "Fumée légère", id = 3 },
        { name = "Stock", id = 4 },
        { name = "Limo", id = 5 },
        { name = "Vert", id = 6 },

    },

    neon = {
        { name = "Blanc", rgb = { 222, 222, 255 } },
        { name = "Bleu", rgb = { 2, 21, 255 } },
        { name = "Bleu électrique", rgb = { 3, 83, 255 } },
        { name = "Vert menthe", rgb = { 1, 255, 140 } },
        { name = "Vert citron", rgb = { 94, 255, 1 } },
        { name = "Jaune", rgb = { 255, 255, 1 } },
        { name = "Golden shower", rgb = { 255, 150, 1 } },
        { name = "Orange", rgb = { 255, 62, 1 } },
        { name = "Rouge", rgb = { 255, 1, 1 } },
        { name = "Rose poney", rgb = { 250, 5, 190 } },
        { name = "Rose vif", rgb = { 255, 5, 190 } },
        { name = "Violet", rgb = { 35, 1, 190 } },
        { name = "Lumière noire", rgb = { 15, 3, 255 } },

    },

    aesthetic = {
        { name = "Aileron", label = 0, index = 1 },
        { name = "Pare-chocs avant", label = 1, index = 1 },
        { name = "Pare-chocs arrière", label = 2, index = 1 },
        { name = "Bas de caisse", label = 3, index = 1 },
        { name = "Echappement", label = 4, index = 1 },
        { name = "Arceaux de securité", label = 5, index = 1 },
        { name = "Grille", label = 6, index = 1 },
        { name = "Capot", label = 7, index = 1 },
        { name = "Aile gauche", label = 8, index = 1 },
        { name = "Aile droite", label = 9, index = 1 },
        { name = "Toit", label = 10, index = 1 },
        { name = "Contours de plaque", label = 25, index = 1 },
        { name = "Calandre", label = 26, index = 1 },
        { name = "Neon interieur", label = 35, index = 1 },
        { name = "Coffre", label = 37, index = 1 },
        { name = "Hydraulique", label = 38, index = 1 },
        { name = "Bloc Moteur", label = 39, index = 1 },
        { name = "Filtre à air", label = 40, index = 1 },
        { name = "Accessoires", label = 41, index = 1 },
        { name = "Cache-roues", label = 42, index = 1 },
        { name = "Antennes", label = 43, index = 1 },
        { name = "Ailes", label = 44, index = 1 },
        { name = "Réservoir", label = 45, index = 1 },
        { name = "Fenêtres", label = 46, index = 1 },
        { name = "Rétroviseurs", label = 47, index = 1 },
    },


    nacrageColor = {
        { name = "Chrome", id = 120 },
        { name = "Noir", id = 0 },
        { name = "Noir carbone", id = 147 },
        { name = "Graphite", id = 1 },
        { name = "Noir anthracite", id = 11 },
        { name = "Acier noir", id = 2 },
        { name = "Acier Sombre", id = 3 },
        { name = "Argent", id = 4 },
        { name = "Argent bleuté", id = 5 },
        { name = "Acier laminé", id = 6 },
        { name = "Ombre argenté", id = 7 },
        { name = "Pierre d'argent", id = 8 },
        { name = "Midnight Silver", id = 9 },
        { name = "Fonte d'argent", id = 10 },
        { name = "Rouge", id = 27 },
        { name = "Rouge torino", id = 28 },
        { name = "Rouge formula", id = 29 },
        { name = "Rouge lave", id = 150 },
        { name = "Rouge flamboyant", id = 30 },
        { name = "Rouge Grâce", id = 31 },
        { name = "Rouge grenat", id = 32 },
        { name = "Sunset Red", id = 33 },
        { name = "Rouge Cabernet", id = 34 },
        { name = "Vin rouge", id = 143 },
        { name = "Rouge bonbon", id = 35 },
        { name = "Rose vif", id = 135 },
        { name = "Pfister Rose", id = 137 },
        { name = "Rose saumon", id = 136 },
        { name = "Sunrise Orange", id = 36 },
        { name = "Orange", id = 38 },
        { name = "Orange vif", id = 138 },
        { name = "Or", id = 99 },
        { name = "Bronze", id = 90 },
        { name = "Jaune", id = 88 },
        { name = "Jaune course", id = 89 },
        { name = "Jaune rosée", id = 91 },
        { name = "Vert foncé", id = 49 },
        { name = "Vert course", id = 50 },
        { name = "Vert mer", id = 51 },
        { name = "Vert olive", id = 52 },
        { name = "Vert vif", id = 53 },
        { name = "Vert essence", id = 54 },
        { name = "Vert lime", id = 92 },
        { name = "Midnight Blue", id = 141 },
        { name = "Bleu galaxy", id = 61 },
        { name = "Bleu foncé", id = 62 },
        { name = "Bleu saxon", id = 63 },
        { name = "Bleu", id = 64 },
        { name = "Bleu marine", id = 65 },
        { name = "Bleu port", id = 66 },
        { name = "Bleu diamant", id = 67 },
        { name = "Bleu surf", id = 68 },
        { name = "Bleu nautique", id = 69 },
        { name = "Bleu course", id = 73 },
        { name = "Bleu ultra", id = 70 },
        { name = "Bleu clair", id = 74 },
        { name = "Brun chocolat", id = 96 },
        { name = "Brun Bison", id = 101 },
        { name = "Marron clair", id = 95 },
        { name = "Marron Feltzer", id = 94 },
        { name = "Érable Brun", id = 97 },
        { name = "Brun hêtre", id = 103 },
        { name = "Brun Sienne", id = 104 },
        { name = "Brun Selle", id = 98 },
        { name = "Brun mousse", id = 100 },
        { name = "Marron Hêtre", id = 102 },
        { name = "Brun paille", id = 99 },
        { name = "Brun sable", id = 105 },
        { name = "Brun blanchi", id = 106 },
        { name = "Schafter Violet", id = 71 },
        { name = "Violet Spinnaker", id = 72 },
        { name = "Midnight Purple", id = 142 },
        { name = "Violet vif", id = 145 },
        { name = "Crème", id = 107 },
        { name = "Blanc glacé", id = 111 },
        { name = "Blanc givré", id = 112 },
        { name = "Noir", id = 12 },
        { name = "Gris", id = 13 },
        { name = "Gris clair", id = 14 },
        { name = "Blanc Glacé", id = 131 },
        { name = "Bleu", id = 83 },
        { name = "Bleu foncé", id = 82 },
        { name = "Midnight Blue", id = 84 },
        { name = "Midnight Purple", id = 149 },
        { name = "Schafter Violet", id = 148 },
        { name = "Rouge", id = 39 },
        { name = "Rouge foncé", id = 40 },
        { name = "Orange", id = 41 },
        { name = "Jaune", id = 42 },
        { name = "Vert lime", id = 55 },
        { name = "Vert", id = 128 },
        { name = "Vert forêt", id = 151 },
        { name = "Vert feuillage", id = 155 },
        { name = "Olive foncé", id = 152 },
        { name = "Terre noire", id = 153 },
        { name = "Tan du désert", id = 154 },
        { name = "Acier brossé", id = 117 },
        { name = "Acier noir brossé", id = 118 },
        { name = "Aluminium brossé", id = 119 },
        { name = "Or pur", id = 158 },
        { name = "Or brossé", id = 159 }
    },

    interior = {

        { name = "Habitacle", id = 27 },
        { name = "Ornements", id = 28 },
        { name = "Tableau de bord", id = 29 },
        { name = "Cadran", id = 30 },
        { name = "Interieur Porte", id = 31 },
        { name = "Siege", id = 32 },
        { name = "Volant", id = 33 },
        { name = "Levier de vitesse", id = 34 },
        { name = "Enceinte", id = 36 },

    },

    plaque = {
        { name = "Couleur plaque", id = 26 },
        { name = "Position plaque", id = 25 }
    }


}
